server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: master
          uri: http://localhost:8082
          predicates:
            - Path=/accounts/**, /items/**, 
        - id: purchase
          uri: http://localhost:8083
          predicates:
            - Path=/purchases/**, /queryPurchases/**
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: master
          uri: http://master:8080
          predicates:
            - Path=/accounts/**, /items/**, 
        - id: purchase
          uri: http://purchase:8080
          predicates:
            - Path=/purchases/**, /queryPurchases/**
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
